### ISSUE TITLE
Question: ROP in C#

### ISSUE THREAD

**Issue by Sinewyk** [swlaschin/Railway-Oriented-Programming-Example#5]
Did you implement a classic imperative architecture in the C# example to highlight the differences, or is it simply hard (impossible) to do ROP in C# ?

For example, I'm comparing the database access layer in [C#](https://github.com/swlaschin/Railway-Oriented-Programming-Example/blob/master/src/CsRopExample/DataAccessLayer/CustomerDao.cs#L30) and in [F#](https://github.com/swlaschin/Railway-Oriented-Programming-Example/blob/1365f86a29c8ef57972d1c9c9c05320a5e6bc75d/src/FsRopExample/DataAccessLayer.fs#L165).

I see nothing stopping me from creating a Result class (which would be a Either monad ?) and try/catching the getById to actually return a Failure no ?

And then pipe it into those functions that can handle the Result type. Sure it wouldn't be as clean as in F# but it would be doable right ?

edit: fixed F# instead of C# last line

**Comment by swlaschin** [comment]
Yes, it's totally doable in C#! I have written some C# code that does demonstrate that -- I'll try to update this repo with it.

**Comment by Sinewyk** [comment]
Thanks =).
